### ISSUE TITLE
Click to close Feature

### ISSUE THREAD

**Issue by NookDev** [kanety/jquery-simple-menu#1]
Thanks for the code I have used it in a project. 

One thing I personally found missing was the ability to close the submenu when clicking on the same link the second time. 

This is important on mobile as the background may be obscured and it forces the user to make a selection to close the dialog.

I added my own functionality separately using a counter.

Just some feedback in case you consider adding it in the future.

Any chance you could eleborate on why this menu is good for SEO in the readme?

**Comment by kanety** [comment]
Thanks for report. The feature was supported in version 0.4.0.

I'm not familiar with SEO.
My guess is that using "rel" attribute in a menu anchor may have some effectiveness for SEO.

**Comment by NookDev** [comment]
Feature added according to dev.
